/* teste
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.time.YearMonth;
import java.util.Calendar;
import javax.swing.JFrame;

/**
 *
 * @author Ederson
 */
public class CalcIdade extends javax.swing.JFrame {

    /**
     * Creates new form CalcIdade
     */
    
    public int year = YearMonth.now().getYear();
    
    public CalcIdade() {
        initComponents();
        panResul.setVisible(false);
        lblAnoatual.setText(Integer.toString(year));

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCalcula = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sldAno = new javax.swing.JSlider();
        lblNasc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAnoatual = new javax.swing.JLabel();
        panResul = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ampul.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 0, 140, 200));

        btnCalcula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcula.setForeground(new java.awt.Color(0, 153, 102));
        btnCalcula.setText("Calcula");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 91, -1, -1));

        jLabel2.setText("Ano nascimento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 54, -1, -1));

        sldAno.setMaximum(2100);
        sldAno.setMinimum(1900);
        sldAno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAnoStateChanged(evt);
            }
        });
        jPanel1.add(sldAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 53, -1, -1));

        lblNasc.setText("1900");
        jPanel1.add(lblNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 54, 39, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ano Atual ==>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 15, -1, -1));

        lblAnoatual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAnoatual.setForeground(new java.awt.Color(102, 51, 0));
        lblAnoatual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnoatual.setText("1900");
        jPanel1.add(lblAnoatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 15, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Você tem ");

        lblIdade.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblIdade.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setText("anos de idade");

        javax.swing.GroupLayout panResulLayout = new javax.swing.GroupLayout(panResul);
        panResul.setLayout(panResulLayout);
        panResulLayout.setHorizontalGroup(
            panResulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panResulLayout.setVerticalGroup(
            panResulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panResulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panResulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdade)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27))
        );

        jPanel1.add(panResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 136, -1, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        // TODO add your handling code here:
        panResul.setVisible(true);
        String nasc = Integer.toString(sldAno.getValue());
        int idade = (year - Integer.parseInt(nasc));
        lblIdade.setText(Integer.toString(idade));
        
    }//GEN-LAST:event_btnCalculaActionPerformed

    private void sldAnoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAnoStateChanged
        // TODO add your handling code here:
        String nasc = Integer.toString(sldAno.getValue());
        lblNasc.setText(nasc);
    }//GEN-LAST:event_sldAnoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcIdade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnoatual;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JPanel panResul;
    private javax.swing.JSlider sldAno;
    // End of variables declaration//GEN-END:variables
}
